# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(511, 429)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btnCh2pp = QtWidgets.QPushButton(self.centralwidget)
        self.btnCh2pp.setObjectName("btnCh2pp")
        self.gridLayout.addWidget(self.btnCh2pp, 2, 1, 1, 1)
        self.btnPytomoview = QtWidgets.QPushButton(self.centralwidget)
        self.btnPytomoview.setObjectName("btnPytomoview")
        self.gridLayout.addWidget(self.btnPytomoview, 2, 0, 1, 1)
        self.btnTempView = QtWidgets.QPushButton(self.centralwidget)
        self.btnTempView.setObjectName("btnTempView")
        self.gridLayout.addWidget(self.btnTempView, 2, 2, 1, 1)
        self.btnFlowView = QtWidgets.QPushButton(self.centralwidget)
        self.btnFlowView.setObjectName("btnFlowView")
        self.gridLayout.addWidget(self.btnFlowView, 2, 3, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 495, 325))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelImg = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelImg.setText("")
        self.labelImg.setObjectName("labelImg")
        self.gridLayout_2.addWidget(self.labelImg, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 4)
        self.btnFile = QtWidgets.QPushButton(self.centralwidget)
        self.btnFile.setObjectName("btnFile")
        self.gridLayout.addWidget(self.btnFile, 1, 3, 1, 1)
        self.inputOpenFile = QtWidgets.QLineEdit(self.centralwidget)
        self.inputOpenFile.setObjectName("inputOpenFile")
        self.gridLayout.addWidget(self.inputOpenFile, 1, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chpack"))
        self.btnCh2pp.setText(_translate("MainWindow", "Ch2pp"))
        self.btnPytomoview.setText(_translate("MainWindow", "Pytomoviwer"))
        self.btnTempView.setText(_translate("MainWindow", "TempView"))
        self.btnFlowView.setText(_translate("MainWindow", "FlowView"))
        self.btnFile.setText(_translate("MainWindow", "File"))
